'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VMAgent.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnAgreeStatus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnAgreeStatus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnUpload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnUpload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmBundles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmBundles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmBundles1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmBundles1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmBundles2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmBundles2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmBundles3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmBundles3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmBundles4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmBundles4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmBundles5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmBundles5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmBundles6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmBundles6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmBundles7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmBundles7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmBundles8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmBundles8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmDigitalGoods() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmDigitalGoods", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmDigitalGoods1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmDigitalGoods1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmDigitalGoods2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmDigitalGoods2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmDigitalGoods3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmDigitalGoods3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmDigitalGoods4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmDigitalGoods4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmDigitalGoods5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmDigitalGoods5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmDigitalGoods6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmDigitalGoods6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmDocumentScanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmDocumentScanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmJawwalBillPayment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmJawwalBillPayment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmJawwalBillPayment1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmJawwalBillPayment1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmJawwalBillPayment2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmJawwalBillPayment2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmJawwalBillPayment3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmJawwalBillPayment3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmJawwalBillPayment4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmJawwalBillPayment4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmJawwalBillPayment5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmJawwalBillPayment5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmJawwalBillPayment6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmJawwalBillPayment6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmMain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmMain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmMenuEKYC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmMenuEKYC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmNewSim() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmNewSim", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmNewSim1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmNewSim1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmNewSim2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmNewSim2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmNewSim3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmNewSim3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmNewSim4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmNewSim4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmNewSim5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmNewSim5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmNewSim6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmNewSim6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmNewSim7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmNewSim7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmNewSim8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmNewSim8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmNewSimTermsAndConditions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmNewSimTermsAndConditions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmPaltelBillPayment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPaltelBillPayment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmPaltelBillPayment1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPaltelBillPayment1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmPaltelBillPayment2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPaltelBillPayment2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmPaltelBillPayment3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPaltelBillPayment3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmPaltelBillPayment4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPaltelBillPayment4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmPleaseWait() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPleaseWait", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmPleaseWaitGIF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPleaseWaitGIF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmPlus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmPlus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmSIMSwap9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmSIMSwap9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmTimeExtension() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmTimeExtension", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmTopUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmTopUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmTopUp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmTopUp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmTopUp2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmTopUp2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmTopUp3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmTopUp3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmVideoRecorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmVideoRecorder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmVideoRecorderHint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmVideoRecorderHint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Home_Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Home_Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HomeEKYC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HomeEKYC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picDocumentUploadedSuccessfully() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picDocumentUploadedSuccessfully", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picNoNoneRenewable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picNoNoneRenewable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picNoRenewable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picNoRenewable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picPassportUploadedSuccessfully() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPassportUploadedSuccessfully", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picVideoUploadedSuccessfully() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picVideoUploadedSuccessfully", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl3G_BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl3G_BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl3GMins_BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl3GMins_BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnlMins_BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnlMins_BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnlPassport_BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnlPassport_BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rbNationalID() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rbNationalID", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rbPassport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rbPassport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
